//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class drug
    {
        public int id { get; set; }
        public string Trade_Name { get; set; }
        public string Company_name { get; set; }
        public Nullable<int> No_of_Units { get; set; }
        public string Pack_in_price_certificate { get; set; }
        public Nullable<double> New_Price { get; set; }
    }
}
